### ISSUE TITLE
webm works, but not mkv and some m2ts

### ISSUE THREAD

**Issue by Amsitram** [qlmedia/qlmedia.github.io#2]
[00448.m2ts.zip](https://github.com/user-attachments/files/15521966/00448.m2ts.zip)
[00448.mkv.zip](https://github.com/user-attachments/files/15521974/00448.mkv.zip)

Hello,

I've tried several mkv and m2ts files, but thumbnails and quicklook don't work with any mkv, and only some m2ts.
Do you think you can fix this?

Thanks for reading :)

**Comment by qlmedia** [comment]
Hi, please send me the output of these commands:
```bash
$ mdls -name kMDItemContentType -name kMDItemContentTypeTree -name kMDItemKind 00448.m2ts
kMDItemContentType     = "public.avchd-mpeg-2-transport-stream"
kMDItemContentTypeTree = (
    "public.avchd-mpeg-2-transport-stream",
    "public.item",
    "public.movie",
    "public.audiovisual-content",
    "public.mpeg-2-transport-stream",
    "public.data",
    "public.content"
)
kMDItemKind            = "MPEG-2 Transport Stream"

$ mdls -name kMDItemContentType -name kMDItemContentTypeTree -name kMDItemKind 00448.mkv
kMDItemContentType     = "org.matroska.mkv"
kMDItemContentTypeTree = (
    "public.item",
    "public.movie",
    "org.matroska.mkv",
    "public.audiovisual-content",
    "public.data",
    "public.content"
)
kMDItemKind            = "Matroska Video File"
```

**Comment by Amsitram** [comment]
Sure

```
mdls -name kMDItemContentType -name kMDItemContentTypeTree -name kMDItemKind 00448.m2ts 
kMDItemContentType     = "public.avchd-mpeg-2-transport-stream"
kMDItemContentTypeTree = (
    "public.avchd-mpeg-2-transport-stream",
    "public.mpeg-2-transport-stream",
    "public.movie",
    "public.audiovisual-content",
    "public.data",
    "public.item",
    "public.content"
)
kMDItemKind            = "M2T(s)"
```

```
mdls -name kMDItemContentType -name kMDItemContentTypeTree -name kMDItemKind 00448.mkv
kMDItemContentType     = "org.matroska.mkv"
kMDItemContentTypeTree = (
    "org.matroska.mkv",
    "public.movie",
    "public.audiovisual-content",
    "public.data",
    "public.item",
    "public.content"
)
kMDItemKind            = "Matroska Video File"
```

**Comment by qlmedia** [comment]
The m2ts format is intercepted within the system and is not given to user extensions, as well as many other formats - mpeg, avi, etc.
Therefore, it is played sometimes when the MacOS system player can play it and, accordingly, the system player control panel is there.
As for the mkv, the attached sample works for me both in the preview and in the icon.
Try loading the VLC player and check if these videos play normally in it.

**Comment by Amsitram** [comment]
After resetting various things and coming back to my session, the mkvs actually work. As for m2ts, your explanations are clear. As this format is generally readable by default with Quick Look, the extensions can't intervene on videos in this format that don't work (I think it's the same principle with txt and pdf files, for example).

Thanks a lot for your help :)

**Comment by qlmedia** [comment]
np, btw you can change .m2ts file extension to any other that is processed. for example, .vlcf extension is reserved for files that are recognized for preview.

**Comment by Amsitram** [comment]
Indeed, I just renamed 00448.m2ts to 00448.mkv and QL works. Impressive
